# Generated by Django 3.2.18 on 2023-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0049_rbac_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblerepository',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
